name: Deploy Frontend to Dev Server

on:
  push:
    branches:
      - develop
      - pre-prod
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Create and update  ENV variables    
      - name: Create .env files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          run: |
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > /var/www/client/.env
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > /var/www/control/.env
            echo "VITE_STRIPE_PK=${{ secrets.VITE_STRIPE_PK }}" >> /var/www/control/.env
            echo "VITE_PAYPAL_CLIENT_ID=${{ secrets.VITE_PAYPAL_CLIENT_ID }}" >> /var/www/control/.env
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > /var/www/tenant/.env

      # Build client
      - name: Install & build client
        working-directory: ./client
        run: |
          npm ci
          npm run build

      # Build control
      - name: Install & build control
        working-directory: ./control
        run: |
          npm ci
          npm run build

      # Build tenant
      - name: Install & build tenant
        working-directory: ./tenant
        run: |
          npm ci
          npm run build

            # Clean target dirs on EC2 before uploading
      - name: Clean target dirs on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/client/*
            sudo rm -rf /var/www/control/*
            sudo rm -rf /var/www/tenant/*

      # Upload client/dist -> /var/www/client
      - name: Upload client to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "client/dist/**"
          target: "/var/www/client"
          strip_components: 2

      # Upload control/dist -> /var/www/control
      - name: Upload control to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "control/dist/**"
          target: "/var/www/control"
          strip_components: 2

      # Upload tenant/dist -> /var/www/tenant
      - name: Upload tenant to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "tenant/dist/**"
          target: "/var/www/tenant"
          strip_components: 2

      # Reload nginx
      - name: Reload nginx on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo nginx -t && sudo systemctl reload nginx
